# Generated by Django 3.0 on 2019-12-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='bidang',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='dokter',
            name='nama',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='dokter',
            name='nomor_telepon',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='obat',
            name='kandungan',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='obat',
            name='khasiat',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='obat',
            name='nama',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='alamat',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='keluhan',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nama',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nomor_telepon',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='resep',
            name='kumpulan_obat',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='resep',
            name='nama',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
