# Generated by Django 3.0 on 2019-12-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hewan',
            name='nama',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='hewan',
            name='species',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='kandang',
            name='isi_kandang',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='kandang',
            name='nama',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='bidang',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='nama',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='nomor_telepon',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='penjaga',
            name='nama',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='penjaga',
            name='nomor_telepon',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
