# Generated by Django 3.0 on 2019-12-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_auto_20191209_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengunjung',
            name='bidang',
        ),
    ]
