# Generated by Django 3.0 on 2019-12-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='no_telepon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='nomor_absen',
            field=models.IntegerField(default=0),
        ),
    ]
