# Generated by Django 3.0 on 2019-12-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0002_auto_20191209_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='no_telepon',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='no_telepon',
        ),
        migrations.AddField(
            model_name='mentee',
            name='nomor_telepon',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='mentor',
            name='nomor_telepon',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='nama_challenge',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='direksi',
            name='jabatan',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='direksi',
            name='nama_lengkap',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='direksi',
            name='no_telepon',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='livecode',
            name='nama_live_code',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='nama_pelajaran',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='nama_lengkap',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='jabatan',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='nama_lengkap',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
